# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

remote_theme: mmistakes/minimal-mistakes@4.24.0
title: Hakurei Shodo
subtitle: Japanese Caligraphy
email: hakurei.shodo@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
# twitter_username: jekyllrb
# github_username:  jekyll
logo: /assets/images/stamp.png
domain: gnarg.github.io
url: https://gnarg.github.io
# baseurl: hakureishodo
repository: gnarg/hakureishodo
atom_feed:
  hide: true
minimal_mistakes_skin: dirt
head_scripts:
  - /assets/js/newrelic.js
signup_icon: <img src="/assets/images/user-plus-solid.svg" width="25" height="25" />

defaults:
  - scope:
      path: ''
    values:
      classes: wide
      author_profile: true
      header:
        overlay_image: /assets/images/IMG_1150.jpeg
      gallery:
        - image_path: /assets/images/IMG_7932.jpeg
          url: /assets/images/IMG_7932.jpeg
        - image_path: /assets/images/IMG_7933.png
          url: /assets/images/IMG_7933.png
        - image_path: /assets/images/IMG_7935.png
          url: /assets/images/IMG_7935.png
        - image_path: /assets/images/IMG_0572.jpeg
          url: /assets/images/IMG_0572.jpeg
        - image_path: /assets/images/fans.jpg
          url: /assets/images/fans.jpg
        - image_path: /assets/images/IMG_1289.jpeg
          url: /assets/images/IMG_1289.jpeg
        - image_path: /assets/images/IMG_8700.jpeg
          url: /assets/images/IMG_8700.jpeg
        - image_path: /assets/images/IMG_8701.png
          url: /assets/images/IMG_8701.png
        - image_path: /assets/images/IMG_8702.png
          url: /assets/images/IMG_8702.png
        - image_path: /assets/images/IMG_1150.jpeg # wide
          url: /assets/images/IMG_1150.jpeg
        # - image_path: /assets/images/IMG_1154.jpeg # wide
        #   url: /assets/images/IMG_1154.jpeg
        - image_path: /assets/images/IMG_1155.jpeg # wide
          url: /assets/images/IMG_1155.jpeg
        - image_path: /assets/images/IMG_5902.jpeg # wide
          url: /assets/images/IMG_5902.jpeg

        - image_path: /assets/images/new-IMG_1707.JPG
          url: /assets/images/new-IMG_1707.JPG
        - image_path: /assets/images/new-IMG_1602.JPG
          url: /assets/images/new-IMG_1602.JPG
        - image_path: /assets/images/new-IMG_1707.JPG
          url: /assets/images/new-IMG_1707.JPG
        - image_path: /assets/images/new-IMG_9988.JPG
          url: /assets/images/new-IMG_9988.JPG

        # - image_path: /assets/images/new-IMG_0295.JPG
        #   url: /assets/images/new-IMG_0295.JPG
        # - image_path: /assets/images/new-IMG_1139.JPG
        #   url: /assets/images/new-IMG_1139.JPG

        - image_path: /assets/images/new-IMG_1370.JPG
          url: /assets/images/new-IMG_1370.JPG
        # - image_path: /assets/images/new-IMG_1477.JPG
        #   url: /assets/images/new-IMG_1477.JPG
        - image_path: /assets/images/new-IMG_9311.JPG
          url: /assets/images/new-IMG_9311.JPG

        # - image_path: /assets/images/IMG_1153.jpeg
        #   url: /assets/images/IMG_1153.jpeg
        # - image_path: /assets/images/performance.jpg
        #   url: /assets/images/performance.jpg
        # - image_path: /assets/images/IMG_0570.jpeg
        #   url: /assets/images/IMG_0570.jpeg
        # - image_path: /assets/images/IMG_7586.png
        #   url: /assets/images/IMG_7586.png

# Build settings
plugins:
  - jekyll-feed
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
#   - .sass-cache/
  - .jekyll-cache/
#   - gemfiles/
  - Gemfile
  - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
